name: Update README with Merged PRs

on:
  push:
    branches: [ main ] # Trigger on push to main branch
  pull_request:
    branches: [ main ] 



jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Update README
        run: python update_readme.py

      - name: Commit changes
        run: |
              git config user.name "github-actions"
              git config user.email "github-actions@github.com"
              
              git add README.md
              
              # Force show the diff before committing (for debugging)
              git diff --cached
              
              # Only commit if there are actual changes
              if git diff --cached --quiet; then
                echo "No changes to commit"
              else
                git commit -m "Update merged PRs list"
                git push
              fi

